### ISSUE TITLE
Network connection timed out. Maybe add mapping cache?

### ISSUE THREAD

**Issue by KnightBlood** [FCWorkgroupMC/F2C#4]
2020-09-05 21:34:36,688 main WARN Advanced terminal features are not available in this environment
[21:34:37] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <player>, --version, HMCL 3.3.172, --gameDir, D:\Minecraft\.minecraft\versions\1.16.2, --assetsDir, D:\Minecraft\.minecraft\assets, --assetIndex, 1.16, --uuid, <uuid>, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.172, --width, 854, --height, 480, --tweakClass, optifine.OptiFineTweaker, --launchTarget, fmlclient, --fml.forgeVersion, 33.0.23, --fml.mcVersion, 1.16.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200812.004259]
[21:34:37] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_241 by Oracle Corporation
[21:34:37] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[21:34:37] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: D:\Minecraft\.minecraft\libraries\optifine\OptiFine\1.16.2_HD_U_G3\OptiFine-1.16.2_HD_U_G3.jar
[21:34:40] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[21:34:40] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Minecraft/.minecraft/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=CLIENT
[21:34:40] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[21:34:43] [main/INFO] [FabricLoader/]: Loading for game Minecraft 1.16.2
[21:34:58] [ForkJoinPool.commonPool-worker-1/ERROR] [io.gi.fc.f2.f2.ut.NetworkUtil/]: Error when connecting to the Internet
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_241] {}
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_241] {}
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_241] {}
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_241] {}
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_241] {}
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_241] {}
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[?:1.8.0_241] {}
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_241] {}
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_241] {}
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_241] {}
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_241] {}
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_241] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167) ~[?:1.8.0_241] {}
	at io.github.fcworkgroupmc.f2c.f2c.util.NetworkUtil$Net$Connection.<init>(NetworkUtil.java:53) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.util.NetworkUtil$Net$Connection.<init>(NetworkUtil.java:47) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.util.NetworkUtil$Net.lambda$connectAsync$2(NetworkUtil.java:116) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_241] {}
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Connection timed out
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.init(IntermediaryToSrgNameMappingService.java:168)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.fcworkgroupmc.f2c.f2c.transformationservices.FabricModTransformationService.beginScanning(FabricModTransformationService.java:147)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.fcworkgroupmc.f2c.f2c.transformationservices.FabricModTransformationService.runScan(FabricModTransformationService.java:152)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.util.concurrent.TimeoutException
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.init(IntermediaryToSrgNameMappingService.java:159)
[21:35:04] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 15 more
Exception in thread "main"

**Comment by KnightBlood** [comment]
which file need to download ？
can i download by myself？

**Comment by KnightBlood** [comment]
the first problem i have solved，but i have new problem

2020-09-05 22:08:16,301 main WARN Advanced terminal features are not available in this environment
[22:08:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <player>, --version, HMCL 3.3.172, --gameDir, D:\Minecraft\.minecraft\versions\1.16.2, --assetsDir, D:\Minecraft\.minecraft\assets, --assetIndex, 1.16, --uuid, <uuid>, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.172, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 33.0.23, --fml.mcVersion, 1.16.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200812.004259]
[22:08:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_241 by Oracle Corporation
[22:08:20] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22:08:21] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Minecraft/.minecraft/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=CLIENT
[22:08:23] [main/INFO] [FabricLoader/]: Loading for game Minecraft 1.16.2
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Connection timed out
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.init(IntermediaryToSrgNameMappingService.java:168)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.fcworkgroupmc.f2c.f2c.transformationservices.FabricModTransformationService.beginScanning(FabricModTransformationService.java:147)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.fcworkgroupmc.f2c.f2c.transformationservices.FabricModTransformationService.runScan(FabricModTransformationService.java:152)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.util.concurrent.TimeoutException
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.init(IntermediaryToSrgNameMappingService.java:159)
[22:08:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 15 more
Exception in thread "main"

**Comment by KnightBlood** [comment]
我觉得应该把要下载的文件缓存到本地
不然按照现在的情况无法 在无网络的情况下玩

**Comment by XiaoPangxie732** [comment]
启动的时候会从GitHub上下载约4MB的混淆映射文件，我限制了15秒下完，下不完就会报错退出。

**Comment by XiaoPangxie732** [comment]
缓存到本地的话，我考虑考虑吧。如果实在下载不完就只能挂梯子了，可以在HMCL的Java虚拟机参数里写-Df2c.proxyHost=<代理服务器地址(本地服务器的话可以不用填)> -Df2c.proxyPort=<代理服务器的端口>

**Comment by XiaoPangxie732** [comment]
然后因为#2 ，现在这个mod也用不了（fabric api跟forge的补丁冲突），除非自己手动把mixin的注入点调整对

**Comment by KnightBlood** [comment]
> 缓存到本地的话，我考虑考虑吧。如果实在下载不完就只能挂梯子了，可以在HMCL的Java虚拟机参数里写-Df2c.proxyHost=<代理服务器地址(本地服务器的话可以不用填)> -Df2c.proxyPort=<代理服务器的端口>

我这边网络就很神奇，早上 网速和网络质量就很好
然后随着时间推移 对github等网站的访问速度和下载速度就会慢慢下降

**Comment by XiaoPangxie732** [comment]
> > 缓存到本地的话，我考虑考虑吧。如果实在下载不完就只能挂梯子了，可以在HMCL的Java虚拟机参数里写-Df2c.proxyHost=<代理服务器地址(本地服务器的话可以不用填)> -Df2c.proxyPort=<代理服务器的端口>
> 
> 我这边网络就很神奇，早上 网速和网络质量就很好
> 然后随着时间推移 对github等网站的访问速度和下载速度就会慢慢下降

我这里巨离谱，墙GitHub，我基本一直挂着梯子
