### ISSUE TITLE
Error when processing obfuscation mappings in 1.15.2-31.2.23+ versions

### ISSUE THREAD

**Issue by KnightBlood** [FCWorkgroupMC/F2C#5]
https://www.curseforge.com/minecraft/mc-mods/modmenu

或许可以集成一个modemenu进来

2020-09-06 04:11:11,597 main WARN Advanced terminal features are not available in this environment
[04:11:11] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <player>, --version, HMCL 3.3.172, --gameDir, D:\Minecraft\.minecraft\versions\1.16.2, --assetsDir, D:\Minecraft\.minecraft\assets, --assetIndex, 1.16, --uuid, <uuid>, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.172, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 33.0.32, --fml.mcVersion, 1.16.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200812.004259]
[04:11:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_241 by Oracle Corporation
[04:11:16] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[04:11:16] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Minecraft/.minecraft/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=CLIENT
[04:11:20] [main/INFO] [FabricLoader/]: Loading for game Minecraft 1.16.2
[04:11:34] [ForkJoinPool.commonPool-worker-2/FATAL] [io.gi.fc.f2.f2.na.IntermediaryToSrgNameMappingService/]: Error when executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_241] {}
	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.lambda$init$8(IntermediaryToSrgNameMappingService.java:153) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) [?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:594) [?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_241] {}
Caused by: java.lang.NullPointerException
	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService$1.rename(IntermediaryToSrgNameMappingService.java:105) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.minecraftforge.srgutils.MappingFile.lambda$rename$15(MappingFile.java:158) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_241] {}
	at net.minecraftforge.srgutils.MappingFile.rename(MappingFile.java:157) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.minecraftforge.srgutils.MappingFile.rename(MappingFile.java:38) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.lambda$null$3(IntermediaryToSrgNameMappingService.java:102) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_241] {}
	... 4 more
[04:11:34] [main/FATAL] [io.gi.fc.f2.f2.na.IntermediaryToSrgNameMappingService/]: Error when executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Mappings are empty, please check your Internet connection
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_241] {}
	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.init(IntermediaryToSrgNameMappingService.java:159) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.transformationservices.FabricModTransformationService.beginScanning(FabricModTransformationService.java:147) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.transformationservices.FabricModTransformationService.runScan(FabricModTransformationService.java:152) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111) ~[modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115) ~[modlauncher-6.1.1.jar:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) [?:1.8.0_241] {}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628) [?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) [?:1.8.0_241] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_241] {}
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}
Caused by: java.lang.RuntimeException: Mappings are empty, please check your Internet connection
	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToMcpNameMappingService.init(IntermediaryToMcpNameMappingService.java:72) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.namemappingservices.IntermediaryToSrgNameMappingService.lambda$init$9(IntermediaryToSrgNameMappingService.java:157) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_241] {}
[04:11:50] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.github.fcworkgroupmc.f2c.f2c.FabricMixinConnector]
[04:11:51] [main/FATAL] [Fabric|Loader/]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: modmenu requires {fabric-resource-loader-v0 @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:621) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.fabric.FabricLoader.loadMods(FabricLoader.java:176) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at io.github.fcworkgroupmc.f2c.f2c.FabricMixinConnector.connect(FabricMixinConnector.java:45) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {re:classloading}
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.initConnectors(MixinConnectorManager.java:96) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:61) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:194) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$12(LaunchPluginHandler.java:97) ~[modlauncher-6.1.1.jar:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_241] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-6.1.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183) ~[f2c-1.15.2-0.1.1-alpha.jar:1.15.2-0.1.1-alpha] {}
	... 15 more

**Comment by XiaoPangxie732** [comment]
f2c我没在1.16上测试过，但看这个报错似乎是对映射表的处理有问题，我回头去改改

**Comment by XiaoPangxie732** [comment]
屮，适用于1.15.2-31.2.23以上的F2C有问题

**Comment by XiaoPangxie732** [comment]
但是最棘手的问题还是#2，只有把#2 解决了这个mod才真正能用
